FROM bitnami/laravel:latest

WORKDIR /var/www/html

# 其他指令，如 RUN, COPY 等


# 环境变量，如果有的话，可以在这里定义，例如：
# ENV APP_ENV=production

# 安装必要的 PHP 扩展和依赖
# RUN apt-get update && apt-get install -y \
#     libfreetype6-dev \
#     libjpeg62-turbo-dev \
#     libpng-dev \
#     && docker-php-ext-install -j$(nproc) iconv \
#     && docker-php-ext-configure gd --with-freetype --with-jpeg \
#     && docker-php-ext-install -j$(nproc) gd \
#     && docker-php-ext-install pdo_mysql

# # 安装 Composer
# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 如果您有本地的应用代码或其他文件需要复制到镜像中，可以使用 COPY 指令
# 例如：
# COPY . /var/www/html

# 如果您的服务需要对外暴露端口，可以使用 EXPOSE 指令
# 例如，如果您的应用运行在 80 端口：
# EXPOSE 80

# CMD 指令定义了容器启动后默认要运行的命令
# 例如，如果您想运行一个 web 服务器：
# CMD ["apache2-foreground"]